### ISSUE TITLE
`NearestRotationMatrix_FOAM` returns `(0, 0, 0, 0, 0, 0, 0, 0, 1)`

### ISSUE THREAD

**Issue by chubei-oppen** [terzakig/sqpnp#15]
When the input to `NearestRotationMatrix_FOAM` is `(0, 0, 0, 0, 0, 0, 0, 0, sqrt(3))`, it will set `r` to `(0, 0, 0, 0, 0, 0, 0, 0, 1)`, crashing the program later. I haven't got time to read the FOAM paper or check the code yet. Just reporting.

**Comment by terzakig** [comment]
Thank you for reporting! Looking into it.

**Comment by mlourakis** [comment]
@[chubei-oppen](https://github.com/chubei-oppen) Your matrix is singular and this should generally not happen in practice.  Could you please share some more details about how you got it? Minimal input reproducing the problem would be great.

**Comment by chubei-oppen** [comment]
Thank you for your response! I'm detecting [AprilTag](https://april.eecs.umich.edu/software/apriltag)s and solving the camera pose from detected corners. This case happens when the camera sees only one tag. I dumped the coordinates that result in the case. Please see https://github.com/oppenfuture/sqpnp/commit/c2785f2b691800e192b08ae524628610952b6e6a for the data.

**Comment by chubei-oppen** [comment]
BTW switching to `NearestRotationMethod::SVD` works.

**Comment by mlourakis** [comment]
Added a fix that falls back to svd for singular matrices
