### ISSUE TITLE
The check inv_detQ >= 1e-6 fails under common input cases

### ISSUE THREAD

**Issue by nathanrgodwin** [terzakig/sqpnp#2]
As the number of points increases, the matrix Q becomes closer to singular. Around 270 points, this causes the check to fail.

More critically, the check can fail under low numbers of points if the values of the projected points are large compared to the number of points. 

A minimal reproduction of this issue is:
```

int main()
{
    std::vector<cv::Point3_<double>> objPoints{
        cv::Point3d(-0.07473859190940857, 0.07473859190940857, 0),
        cv::Point3d(0.07473859190940857, 0.07473859190940857, 0),
        cv::Point3d(0.07473859190940857, -0.07473859190940857, 0),
        cv::Point3d(-0.07473859190940857, -0.07473859190940857, 0)
    };

    std::vector<cv::Point2d> projPoints{
        cv::Point2d(-11.53961181640625, -10.31392955780029),
        cv::Point2d(-9.844753265380859, -8.958239555358887),
        cv::Point2d(-322.693115234375, -406.5050659179688),
        cv::Point2d(-250.9387664794922, -295.6614990234375)
    };

    sqpnp::PnPSolver solver(objPoints, projPoints);
    if (solver.IsValid())
    {
        solver.Solve();
    }
    else
    {
        std::cerr << "Failed to initialize solver" << std::endl;
    }
}
```

The points provided here are solvable using all other solvePnP algorithms in the OpenCV library. After skipping the check and inverting the matrix, the solver completes successfully with low error.

**Comment by terzakig** [comment]
Thanks, yes, I can see the issue. I was hoping that this check would pick up degenerate formations of the 3D points ( 3 points haveing the same coordinate n = 3) so that they can be avoided during RANSAC. I will either replace it with separate check of the 3D point having the same coordinates or being on a line. All in all, I think this check can be skipped.

**Comment by terzakig** [comment]
It appears that this was a bug as the intent was to check for near-zero determinant (and not the opposite). Regardless, the latest commit should have rectified this issue without having to sacrifice this check. Thanks for noticing!
