### ISSUE TITLE
May I ask if the sqpnp algorithm can run with high accuracy at a distance of about a hundred meters? Ten identification points make up a small proportion of the camera's field of view

### ISSUE THREAD

**Issue by cvDFT** [terzakig/sqpnp#21]
As shown in the title, the performance of my project's PNP algorithm is not as expected

**Comment by terzakig** [comment]
Hi there,

thanks for your interest in our work!

Distance is not an issue for the PnP in general. However, not accounting for noise, it can pose a problem if, for instance, your sensor's resolution cannot "distinguish" the projections of the 3D points from some degenerate configuration, say, a line or a point. For example, if the 3D points are arranged on the corners of a square with 50cm side at 100m from the camera, then these points may end up projected near or on a single pixel in your camera.

Other issue is "noise". If your projections are distinguishable enough, then error in the PnP estimate may be attributed to small errors in the pixel locations, which are pronounced even more at 100m distance. But this is less problematic than degenerate artrangements.

Hope the above helps
________________________________
From: cvDFT ***@***.***>
Sent: Thursday, September 7, 2023 1:54 PM
To: terzakig/sqpnp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [terzakig/sqpnp] May I ask if the sqpnp algorithm can run with high accuracy at a distance of about a hundred meters? Ten identification points make up a small proportion of the camera's field of view (Issue #21)


As shown in the title, the performance of my project's PNP algorithm is not as expected

**Comment by cvDFT** [comment]
Thank you very much for your reply, but I see a saying that measuring distance is the primary factor affecting measurement accuracy, and the measurement error of the Z-axis shows exponential growth. As with this viewpoint, I am using the corner of the object on the right side of this image to measure the camera's rotation matrix, which has a significant error.
![8e2882319a2a1360fa72dcfdbe122dc](https://github.com/terzakig/sqpnp/assets/94675255/f022ea06-5386-448b-a84f-4fca9d5a84b0)

**Comment by cvDFT** [comment]
Thank you for your outstanding work. I should also be researching a field wide field calibration scheme myself.
